import CursorFollower from "@/app/_components/Cursor/CursorFollower";
import Footer from "@/app/_components/Footer/Footer";
import { CursorSizeProvider } from "@/app/_components/Cursor/CursorBtn";

export const metadata = {
    title: "Itsuki-portfolio.js",
    description: "Generated by Next.js",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <head>
                <link rel="icon" sizes="32x32" href="/itsuki.png" />
            </head>
            <body>
                {/* CursorSizeProvider で全体をラップ */}
                <CursorSizeProvider>
                    <CursorFollower />
                    {children}
                </CursorSizeProvider>
            </body>
        </html>
    );
}
