export const metadata = {
  title: 'Itsuki-portfolio.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" sizes="32x32" href="/dot-itsuki-icon.jpg" />
      </head>
      <body>{children}</body>
    </html>
  )
}
